#ifndef RESOURCE_H
#define RESOURCE_H

#define IDC_TAB_CONTROL             1001
#define IDC_TAB_BASIC               1002
#define IDC_TAB_NETWORK             1003
#define IDC_TAB_DOWNLOADER          1004
#define IDC_TAB_PROCESSING          1005
#define IDC_TAB_ADVANCED            1006

#define IDC_URL_EDIT                1010
#define IDC_SAVEPATH_EDIT           1011
#define IDC_BROWSE_BTN              1012
#define IDC_FORMAT_COMBO            1013
#define IDC_QUALITY_COMBO           1014

#define IDC_PROXY_EDIT              1020
#define IDC_COOKIES_BROWSER_COMBO   1021
#define IDC_COOKIES_FILE_EDIT       1022
#define IDC_COOKIES_FILE_BROWSE_BTN 1023

#define IDC_DOWNLOADER_COMBO        1030
#define IDC_DOWNLOADER_ARGS_EDIT    1031

#define IDC_MERGE_FORMAT_COMBO      1040
#define IDC_CONVERT_SUBS_COMBO      1041
#define IDC_CONVERT_THUMBNAILS_COMBO 1042
#define IDC_EMBED_SUBS_CHECK        1043
#define IDC_EMBED_THUMBNAIL_CHECK   1044
#define IDC_EMBED_METADATA_CHECK    1045
#define IDC_EMBED_CHAPTERS_CHECK    1046
#define IDC_SPLIT_CHAPTERS_CHECK    1047

#define IDC_IGNORE_CONFIG_CHECK     1050
#define IDC_LIVE_FROM_START_CHECK   1051
#define IDC_CHECK_FORMATS_CHECK     1052
#define IDC_SKIP_DOWNLOAD_CHECK     1053
#define IDC_SAVE_JSON_CHECK         1054
#define IDC_LIST_FORMATS_CHECK      1055
#define IDC_BATCH_FILE_EDIT         1056
#define IDC_BATCH_FILE_BROWSE_BTN   1057
#define IDC_OUTPUT_TEMPLATE_EDIT    1058
#define IDC_REMOVE_CHAPTERS_EDIT    1059

#define IDC_PROGRESS_BAR            1060
#define IDC_OUTPUT_EDIT             1061
#define IDC_TOGGLE_OUTPUT_BTN       1062
#define IDC_DOWNLOAD_BTN            1063

#endif // RESOURCE_H
