name: Build C++ Windows GUI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          
    - name: Build the application
      shell: msys2 {0}
      run: |
        g++ main.cpp -o yt-dlp-gui.exe \
          -std=c++17 \
          -mwindows \
          -lcomctl32 \
          -lole32 \
          -lshell32 \
          -static-libgcc \
          -static-libstdc++ \
          -Wl,-subsystem,windows

    - name: Prepare artifact
      shell: bash
      run: |
        mkdir release
        mv yt-dlp-gui.exe release/
        echo "Place yt-dlp.exe and ffmpeg.exe (optional, for merging formats) in this folder." > release/README.txt
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: yt-dlp-gui-windows
        path: release/
