name: Build qwen yt-dlp GUI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install MinGW-w64
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    

    - name: Build
      run: |
        g++ -static -std=c++17 -DUNICODE -D_UNICODE -mwindows -o yt-dlp-gui.exe src/main.cpp -lcomctl32 -lole32 -loleaut32

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: yt-dlp-gui
        path: yt-dlp-gui.exe
