name: Build qwen yt-dlp GUI (MSVC)

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Compile with MSVC (cl.exe)
        run: |
          cl.exe /std:c++17 /EHsc /DUNICODE /D_UNICODE /O2 /link /SUBSYSTEM:WINDOWS /OUT:yt-dlp-gui.exe src\main.cpp comctl32.lib

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yt-dlp-gui-windows
          path: yt-dlp-gui.exe
