name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Версия (v1.2.3)'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore youtube-dl-gui.sln || echo "No packages to restore"

      # 🗓 Генерация BuildDate.txt в нужном формате YYYY-MM-DD
      - name: Set Build Date
        run: |
          $date = Get-Date -Format "yyyy-MM-dd"
          Set-Content -Path "youtube-dl-gui/Resources/BuildDate.txt" -Value $date
        shell: pwsh

      # 📦 Сборка updater
      - name: Build Updater
        run: msbuild youtube-dl-gui-updater\youtube-dl-gui-updater.csproj /t:Build /p:Configuration=Release /p:Platform="Any CPU" /p:RunPreBuildEvent=Never

      # 🖥 Сборка GUI
      - name: Build GUI
        run: msbuild youtube-dl-gui\youtube-dl-gui.csproj /t:Build /p:Configuration=Release /p:Platform="Any CPU" /p:RunPreBuildEvent=Never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: |
            youtube-dl-gui\bin\Release\**
            youtube-dl-gui-updater\bin\Release\**
            Release\**

  release:
    runs-on: windows-2022
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-build
          path: ./build

      - name: Create GitHub Release
        id: publish
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          fail_on_unmatched_files: true
          files: ./build/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      assets: ${{ steps.publish.outputs.assets }}
